import 'package:flutter/material.dart';

/// App Localizations - Simple localization system for EN/ID
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Fasnota',
      'welcome_subtitle': 'Manage invoices easily,\nfast, and professional.',
      'get_started': 'GET STARTED',
      'invoices': 'Invoices',
      'invoice_total': 'invoice total',
      'create_invoice': 'Create Invoice',
      'edit_invoice': 'Edit Invoice',
      'customer_info': 'Customer Info',
      'customer_name': 'Customer Name *',
      'customer_name_required': 'Name is required',
      'customer_address': 'Address',
      'email': 'Email',
      'phone': 'Phone',
      'date_status': 'Date & Status',
      'date': 'Date',
      'due_date': 'Due Date',
      'status': 'Status',
      'product_items': 'Product Items',
      'no_items': 'No items yet',
      'add_item': 'Add Item',
      'select_from_products': 'Select from Products',
      'create_new_item': 'Create New Item',
      'product_name': 'Product Name',
      'price': 'Price',
      'qty': 'Qty',
      'required_field': 'Required',
      'add': 'Add',
      'cancel': 'Cancel',
      'tax_discount': 'Tax & Discount',
      'tax_percent': 'Tax (%)',
      'discount': 'Discount',
      'notes': 'Notes',
      'subtotal': 'Subtotal',
      'grand_total': 'Grand Total',
      'save_invoice': 'Save Invoice',
      'update_invoice': 'Update Invoice',
      'failed_save': 'Failed to save invoice',
      'add_min_item': 'Add at least 1 item',
      'detail_invoice': 'Invoice Detail',
      'export_pdf': 'Export PDF',
      'share': 'Share',
      'edit': 'Edit',
      'delete': 'Delete',
      'delete_invoice': 'Delete Invoice',
      'delete_confirm': 'Are you sure you want to delete this invoice? This action cannot be undone.',
      'share_invoice': 'Share Invoice',
      'whatsapp': 'WhatsApp',
      'share_whatsapp': 'Send summary via WhatsApp',
      'email_share': 'Email',
      'send_pdf_email': 'Send PDF via email',
      'share_pdf': 'Share PDF File',
      'share_pdf_desc': 'Share PDF file to other apps',
      'mark_paid': 'Mark as Paid',
      'mark_unpaid': 'Mark as Unpaid',
      'overdue_label': 'Overdue',
      'days_left': 'days left',
      'due_today': 'Due today',
      'late_days': 'days late',
      'payment_summary': 'Payment Summary',
      'search_invoice': 'Search invoice...',
      'not_found': 'Not Found',
      'try_change_search': 'Try changing keywords or search filter.',
      'no_invoices': 'No Invoices Yet',
      'create_first': 'Create your first invoice to get started.',
      'all': 'All',
      'unpaid': 'Unpaid',
      'paid': 'Paid',
      'overdue': 'Overdue',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'dark_mode_active': 'Dark mode is active',
      'light_mode_active': 'Light mode is active',
      'language': 'Language',
      'language_desc': 'Select application language',
      'business_profile': 'Business Profile',
      'business_profile_desc': 'Customize your invoice info',
      'business_name': 'Business Name',
      'business_address': 'Business Address',
      'business_phone': 'Business Phone',
      'business_email': 'Business Email',
      'bank_name': 'Bank Name',
      'bank_account': 'Bank Account Number',
      'bank_holder': 'Account Holder Name',
      'profile_notes': 'Additional Notes',
      'save': 'Save',
      'items_products': 'Items / Products',
      'clients_contacts': 'Clients / Contacts',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'product_photo': 'Product Photo',
      'take_photo': 'Take Photo',
      'gallery': 'Gallery',
      'delete_product': 'Delete Product',
      'delete_product_confirm': 'Are you sure you want to delete this product?',
      'no_products': 'No Products Yet',
      'create_first_product': 'Create your first product to get started.',
      'add_client': 'Add Client',
      'edit_client': 'Edit Client',
      'delete_client': 'Delete Client',
      'delete_client_confirm': 'Are you sure you want to delete this client?',
      'no_clients': 'No Clients Yet',
      'create_first_client': 'Create your first client to get started.',
      'client_name': 'Client Name *',
      'client_address': 'Address',
      'client_phone': 'Phone',
      'client_email': 'Email',
      'select_customer': 'Select Customer',
      'create_new_customer': 'Create New',
      'select_saved': 'Select from Saved',
      'notifications': 'Notifications',
      'notification_reminder': 'Reminder',
      'notification_overdue': 'Overdue',
      'days_before_due': 'days before due',
      'invoice_overdue_notif': 'Invoice is overdue!',
      'invoice_reminder_notif': 'Invoice due reminder',
      'select_product': 'Select Product',
      'search_products': 'Search products...',
      'search_clients': 'Search clients...',
      'thank_you': 'Thank you for your trust.',
      'auto_generated': 'Fasnota - Auto generated',
      'pdf_export': 'Export PDF',
      'pdf_desc': 'Invoice automatically in professional PDF format',
      'share_feature': 'Share Invoice',
      'share_desc': 'Share via WhatsApp, Email, or PDF file',
      'search_filter': 'Search & Filter',
      'search_filter_desc': 'Search invoices by name, number, or phone',
      'status_tracking': 'Invoice Status',
      'status_tracking_desc': 'Paid, Unpaid, and Overdue tracking',
      'features': 'Features',
      'version': 'App Version',
    },
    'id': {
      'app_title': 'Fasnota',
      'welcome_subtitle': 'Kelola invoice dengan mudah,\ncepat, dan profesional.',
      'get_started': 'MULAI',
      'invoices': 'Invoice',
      'invoice_total': 'invoice total',
      'create_invoice': 'Buat Invoice',
      'edit_invoice': 'Edit Invoice',
      'customer_info': 'Info Pelanggan',
      'customer_name': 'Nama Pelanggan *',
      'customer_name_required': 'Nama wajib diisi',
      'customer_address': 'Alamat',
      'email': 'Email',
      'phone': 'Telepon',
      'date_status': 'Tanggal & Status',
      'date': 'Tanggal',
      'due_date': 'Jatuh Tempo',
      'status': 'Status',
      'product_items': 'Item Produk',
      'no_items': 'Belum ada item',
      'add_item': 'Tambah Item',
      'select_from_products': 'Pilih dari Produk',
      'create_new_item': 'Buat Item Baru',
      'product_name': 'Nama Produk',
      'price': 'Harga',
      'qty': 'Qty',
      'required_field': 'Wajib diisi',
      'add': 'Tambah',
      'cancel': 'Batal',
      'tax_discount': 'Pajak & Diskon',
      'tax_percent': 'Pajak (%)',
      'discount': 'Diskon',
      'notes': 'Catatan',
      'subtotal': 'Subtotal',
      'grand_total': 'Grand Total',
      'save_invoice': 'Simpan Invoice',
      'update_invoice': 'Update Invoice',
      'failed_save': 'Gagal menyimpan invoice',
      'add_min_item': 'Tambahkan minimal 1 item',
      'detail_invoice': 'Detail Invoice',
      'export_pdf': 'Export PDF',
      'share': 'Bagikan',
      'edit': 'Edit',
      'delete': 'Hapus',
      'delete_invoice': 'Hapus Invoice',
      'delete_confirm': 'Yakin ingin menghapus invoice ini? Aksi ini tidak dapat dibatalkan.',
      'share_invoice': 'Bagikan Invoice',
      'whatsapp': 'WhatsApp',
      'share_whatsapp': 'Kirim ringkasan via WhatsApp',
      'email_share': 'Email',
      'send_pdf_email': 'Kirim PDF via email',
      'share_pdf': 'Bagikan File PDF',
      'share_pdf_desc': 'Bagikan file PDF ke aplikasi lain',
      'mark_paid': 'Tandai Sudah Dibayar',
      'mark_unpaid': 'Tandai Belum Bayar',
      'overdue_label': 'Terlambat',
      'days_left': 'hari lagi',
      'due_today': 'Jatuh tempo hari ini',
      'late_days': 'hari terlambat',
      'payment_summary': 'Ringkasan Pembayaran',
      'search_invoice': 'Cari invoice...',
      'not_found': 'Tidak Ditemukan',
      'try_change_search': 'Coba ubah kata kunci atau filter pencarian.',
      'no_invoices': 'Belum Ada Invoice',
      'create_first': 'Buat invoice pertama Anda untuk memulai.',
      'all': 'Semua',
      'unpaid': 'Belum Bayar',
      'paid': 'Lunas',
      'overdue': 'Terlambat',
      'settings': 'Pengaturan',
      'appearance': 'Tampilan',
      'dark_mode': 'Mode Gelap',
      'dark_mode_active': 'Mode gelap sedang aktif',
      'light_mode_active': 'Mode terang sedang aktif',
      'language': 'Bahasa',
      'language_desc': 'Pilih bahasa aplikasi',
      'business_profile': 'Profil Usaha',
      'business_profile_desc': 'Kustomisasi info nota/invoice',
      'business_name': 'Nama Usaha',
      'business_address': 'Alamat Usaha',
      'business_phone': 'Telepon Usaha',
      'business_email': 'Email Usaha',
      'bank_name': 'Nama Bank',
      'bank_account': 'Nomor Rekening',
      'bank_holder': 'Nama Pemilik Rekening',
      'profile_notes': 'Catatan Tambahan',
      'save': 'Simpan',
      'items_products': 'Data Barang',
      'clients_contacts': 'Kontak Pelanggan',
      'add_product': 'Tambah Produk',
      'edit_product': 'Edit Produk',
      'product_photo': 'Foto Produk',
      'take_photo': 'Ambil Foto',
      'gallery': 'Galeri',
      'delete_product': 'Hapus Produk',
      'delete_product_confirm': 'Yakin ingin menghapus produk ini?',
      'no_products': 'Belum Ada Produk',
      'create_first_product': 'Buat produk pertama Anda untuk memulai.',
      'add_client': 'Tambah Klien',
      'edit_client': 'Edit Klien',
      'delete_client': 'Hapus Klien',
      'delete_client_confirm': 'Yakin ingin menghapus klien ini?',
      'no_clients': 'Belum Ada Klien',
      'create_first_client': 'Buat klien pertama Anda untuk memulai.',
      'client_name': 'Nama Klien *',
      'client_address': 'Alamat',
      'client_phone': 'Telepon',
      'client_email': 'Email',
      'select_customer': 'Pilih Pelanggan',
      'create_new_customer': 'Buat Baru',
      'select_saved': 'Pilih dari Tersimpan',
      'notifications': 'Notifikasi',
      'notification_reminder': 'Pengingat',
      'notification_overdue': 'Terlambat',
      'days_before_due': 'hari sebelum jatuh tempo',
      'invoice_overdue_notif': 'Invoice sudah melewati jatuh tempo!',
      'invoice_reminder_notif': 'Pengingat jatuh tempo invoice',
      'select_product': 'Pilih Produk',
      'search_products': 'Cari produk...',
      'search_clients': 'Cari klien...',
      'thank_you': 'Terima kasih atas kepercayaan Anda.',
      'auto_generated': 'Fasnota - Dibuat secara otomatis',
      'pdf_export': 'Export PDF',
      'pdf_desc': 'Invoice otomatis dalam format PDF profesional',
      'share_feature': 'Share Invoice',
      'share_desc': 'Bagikan via WhatsApp, Email, atau file PDF',
      'search_filter': 'Pencarian & Filter',
      'search_filter_desc': 'Cari invoice berdasarkan nama, nomor, atau telepon',
      'status_tracking': 'Status Invoice',
      'status_tracking_desc': 'Paid, Unpaid, dan Overdue tracking',
      'features': 'Fitur',
      'version': 'Versi Aplikasi',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'id'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
